---
- name: Configure workstation VM
  hosts: localhost
  vars:
    git:
      - name: user.name
        value: Michael Phillips
      - name: user.email
        value: miphilli@redhat.com
      - name: push.default
        value: simple
      - name: credential.https://github.com.username
        value: angelesphillips
  tasks:
    - name: Install software
      yum:
        name:
          - python-psutil
          - gnome-tweak-tool
        state: latest

    - name: Make Regular Directories
      file:
        path: "{{ item }}"
        state: directory
        owner: student
        group: student
        mode: '0775'
      loop:
        - /home/student/bin

    - name: Make Secure Directories
      file:
        path: "{{ item }}"
        state: directory
        owner: student
        group: student
        mode: '0700'
      loop:
        - /home/student/.config

    - name: Configure aliases
      blockinfile:
        path: /home/student/.bashrc
        marker: "# {mark} ANSIBLE MANAGED BLOCK ALIASES"
        block: "{{ lookup('file', 'files/bashrc_aliases') }}"
        owner: student
        group: student
        mode: '0644'
        state: present

    - name: Copy my-gsettings.sh
      copy:
        src: files/my-gsettings.sh
        dest: /home/student/bin/my-gsettings.sh
        owner: student
        group: student
        mode: '0755'

    - name: Run my-gsettings.sh
      become: true
      become_user: student
      changed_when: false
      command: /home/student/bin/my-gsettings.sh

    - name: Configure basic git settings
      git_config:
        scope: global
        name: "{{ item['name'] }}"
        value: "{{ item['value'] }}"
      loop: "{{ git }}"
      tags: git

    - name: Customize .vimrc
      become: true
      become_user: student
      copy:
        content: "set ai et ts=2 sts=2 sw=2 colorcolumn=80"
        dest: /home/student/.vimrc
        owner: student
        group: student
        mode: '0644'
