---
- name: Customize Workstation
  hosts: localhost
  roles:
    - powerline
  vars_files:
    - vars.yml
  tasks:
    - name: Install packages
      become: true
      package:
        name: pre-commit
        state: latest
    - name: Adds user to sudoers
      become: true
      user:
        name: "{{ ansible_facts['user_id'] }}"
        groups: wheel
        append: yes
    - name: Configure basic git settings
      git_config:
        scope: global
        name: "{{ item['name'] }}"
        value: "{{ item['value'] }}"
      loop: "{{ git }}"
      when: git is defined
    - name: Create file
      copy:
        dest: ~{{ ansible_env['USER'] }}/.ssh/id_rsa
        content: "{{ ghkey }}"
        mode: 0400
      when: ghkey is defined